name: CI

on:
  push:
    branches: [main]

jobs:
  Deploy-Action:
    name: CI-Deploy-Action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'github-host'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_IP_DIGITALOCEAN }} >> ~/.ssh/known_hosts
      - run: npm ci
      - run: npm run build --if-present
      - run: ssh github@${{ secrets.SSH_IP_DIGITALOCEAN }} "rm -rf /var/www/fayevr.dev/httpdocs/* && exit"
      - run: scp -r ./build/* github@${{ secrets.SSH_IP_DIGITALOCEAN }}:/var/www/fayevr.dev/httpdocs
